name: AppImage Build
on:
  release:
    types: [created, edited]
    
  push:
    paths-ignore: # Не перестраивайте, если изменилась только документация
      - "**.md"
  
  pull_request:
  workflow_dispatch:
    #inputs:
      #tag:
        #description: 'Release tag'
        #required: true

jobs:
  build:
    runs-on: ubuntu-20.04
  
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master

    - name: Install required dependencies (as Dockerfile)
      run: sudo apt-get install --yes locales wget build-essential

    - name: Executing AppImage build
      run: bash ./make_appimage.sh
  
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        tag: ${{ github.event.inputs.tag }}
        name: "Release build (${{ github.event.inputs.tag }})"
        artifacts: "Geany*.AppImage"
        token: ${{ secrets.GITHUB_TOKEN }}
